-- MySQL Workbench Synchronization
-- Generated: 2024-03-08 13:48
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Tek-System

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `publicationYear` INT(11) NULL DEFAULT NULL,
  `copies` INT(11) NULL DEFAULT NULL,
  `avaliableCopies` INT(11) NULL DEFAULT NULL,
  `bookscol` VARCHAR(45) NULL DEFAULT NULL,
  `categoryId` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `categoryId`),
  INDEX `fk_books_categories_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_books_categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
